FROM node:20 AS test-stage

WORKDIR /usr/src/app

COPY . .

RUN npm ci

RUN npm run test


FROM node:20 AS build-stage

WORKDIR /usr/src/app

COPY --from=test-stage /usr/src/app /usr/src/app

RUN npm ci

ENV VITE_BACKEND_URL=http://localhost:8080/api/  
# http://localhost:3000

RUN npm run build

# This is a new stage, everything before this is gone, except for the files that we want to COPY
FROM nginx:1.25-alpine

# COPY the directory dist from the build-stage to /usr/share/nginx/html
# The target location here was found from the Docker hub page
COPY --from=build-stage /usr/src/app/dist /usr/share/nginx/html

# docker build  -f Dockerfile_nginx -t todo-front_nginx .  # . - is always last (or $(pwd)
# docker run  -p 8000:80  todo-front_nginx